/**
 * AI-Friendly Codebase Unit Tests
 * Feature: ai-friendly-codebase
 *
 * Verifies specific section markers in key pages, dynamic CSS selectors
 * retained with comments, architectural decisions has initial entries,
 * and image inventory includes recommendation data.
 */
import { describe, it, expect } from "vitest";
import fs from "fs";
import { resolve } from "path";

/** Read a file relative to project root. */
function read(filePath) {
  return fs.readFileSync(resolve(filePath), "utf-8");
}

// ─── 1. Section markers in key pages ─────────────────────────────────────────

describe("Section markers in key pages", () => {
  describe("index.html", () => {
    const content = read("index.html");

    it('has "Banner" section marker', () => {
      expect(content).toMatch(/<!-- Section: Banner -->/);
      expect(content).toMatch(/<!-- \/Section: Banner -->/);
    });

    it('has "Features" section marker', () => {
      expect(content).toMatch(/<!-- Section: Features -->/);
      expect(content).toMatch(/<!-- \/Section: Features -->/);
    });

    it('has "Livestream" section marker', () => {
      expect(content).toMatch(/<!-- Section: Livestream -->/);
      expect(content).toMatch(/<!-- \/Section: Livestream -->/);
    });
  });

  describe("donate.html", () => {
    const content = read("donate.html");

    it('has "Square Donation" section marker', () => {
      expect(content).toMatch(/<!-- Section: Square Donation -->/);
      expect(content).toMatch(/<!-- \/Section: Square Donation -->/);
    });

    it('has "PayPal Donation" section marker', () => {
      expect(content).toMatch(/<!-- Section: PayPal Donation -->/);
      expect(content).toMatch(/<!-- \/Section: PayPal Donation -->/);
    });

    it('has "Zelle Donation" section marker', () => {
      expect(content).toMatch(/<!-- Section: Zelle Donation -->/);
      expect(content).toMatch(/<!-- \/Section: Zelle Donation -->/);
    });
  });

  describe("header.html", () => {
    const content = read("header.html");

    it('has "Logo" section marker', () => {
      expect(content).toMatch(/<!-- Section: Logo -->/);
      expect(content).toMatch(/<!-- \/Section: Logo -->/);
    });

    it('has "Navigation" section marker', () => {
      expect(content).toMatch(/<!-- Section: Navigation -->/);
      expect(content).toMatch(/<!-- \/Section: Navigation -->/);
    });
  });

  describe("footer.html", () => {
    const content = read("footer.html");

    it('has "Sitemap" section marker', () => {
      expect(content).toMatch(/<!-- Section: Sitemap -->/);
      expect(content).toMatch(/<!-- \/Section: Sitemap -->/);
    });

    it('has "Contact" section marker', () => {
      expect(content).toMatch(/<!-- Section: Contact -->/);
      expect(content).toMatch(/<!-- \/Section: Contact -->/);
    });

    it('has "Copyright" section marker', () => {
      expect(content).toMatch(/<!-- Section: Copyright -->/);
      expect(content).toMatch(/<!-- \/Section: Copyright -->/);
    });
  });
});

// ─── 2. Dynamic CSS selectors retained with comments ─────────────────────────

describe("Dynamic CSS selectors in _responsive.css", () => {
  const content = read("assets/css/modules/_responsive.css");

  it('contains "/* Dynamic: generated by main.js */" comment', () => {
    expect(content).toContain("/* Dynamic: generated by main.js */");
  });

  it("contains #navPanel selector", () => {
    expect(content).toMatch(/#navPanel/);
  });

  it("contains #navToggle selector", () => {
    expect(content).toMatch(/#navToggle/);
  });

  it("contains .navPanel-visible reference", () => {
    expect(content).toMatch(/\.navPanel-visible/);
  });
});

// ─── 3. Architectural decisions has initial entries ──────────────────────────

describe("Architectural decisions initial entries", () => {
  const content = read(".kiro/steering/architectural-decisions.md");

  it('contains "Quran PDF Viewer" entry', () => {
    expect(content).toMatch(/Quran.*Viewer/i);
  });

  it('contains "Donation Receipts" entry', () => {
    expect(content).toMatch(/Donation Receipts/i);
  });

  it('contains "Matrimonial" entry', () => {
    expect(content).toMatch(/Matrimonial/i);
  });

  it('contains "WAI-ARIA" or "Dropotron" entry', () => {
    expect(content).toMatch(/WAI-ARIA|Dropotron/i);
  });

  it('contains "Playfair Display" entry', () => {
    expect(content).toMatch(/Playfair Display/);
  });

  it('contains "Navy" or "navy" (color palette)', () => {
    expect(content).toMatch(/[Nn]avy/);
  });

  it("each entry has a date pattern (YYYY-MM-DD)", () => {
    const datePattern = /\d{4}-\d{2}-\d{2}/g;
    const dates = content.match(datePattern);
    expect(dates).not.toBeNull();
    expect(dates.length).toBeGreaterThanOrEqual(6);
  });
});

// ─── 4. Image inventory includes recommendation data ─────────────────────────

describe("Image inventory recommendation data", () => {
  const content = read(".kiro/steering/image-inventory.md");

  it('contains "sisters-hero.jpg" (suggested future image)', () => {
    expect(content).toContain("sisters-hero.jpg");
  });

  it('contains "youth-hero.jpg" (suggested future image)', () => {
    expect(content).toContain("youth-hero.jpg");
  });

  it('contains "Unsplash" (image source recommendation)', () => {
    expect(content).toContain("Unsplash");
  });

  it('contains "16:9" (aspect ratio recommendation)', () => {
    expect(content).toContain("16:9");
  });
});
